### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by ghost** [jiacai2050/text-saver#1]
Hi,

Text saver 1.3.1 / Firefox 111.0 running flawlessly. A welcomed extension. Handy.

Maybe a few suggestions ...

1- _**Changelog**_ availability : none on AMO, here the latest concerns version 2.0. What's new with later versions up to current 1.3.1?
2- **_The extension itself:_**
2.1- A dark mode independently of the browser's policy would be welcomed. At this time I use a dedicated userContent.css and the rendering is nice.
2.2- The _Created at_ date and time formats : YYYY/MM/DD (international) and 24hrs rather than AM/PM would IMO be an improvement.
2.3- An Import feature; We have _Export_, but no Import.

Thanks!

**Comment by jiacai2050** [comment]
Hi, lots of good suggestions, thanks.

You can find changelog here 
- https://github.com/jiacai2050/text-saver/releases

 Although not complete, I will highlight important changes.
- Dark mode/Import sounds a very good feature, I will create new issue to track them. #2  #3 
- Time format is using [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString), so this may depend on how locale is set on your machine?

**Comment by ghost** [comment]
Just updated _Text Saver_ to version _**1.4.0**_ which fulfills practically all my suggestions/wishes. Nice work.

**Comment by jiacai2050** [comment]
Glad it helps, feel free to open new issue if you have more suggestions.
