### ISSUE TITLE
Does not appear in right-text menu

### ISSUE THREAD

**Issue by AndLeaveATrail** [jiacai2050/text-saver#5]
### Describe this problem

Does not appear in right-text menu. I've enabled all permissions, restarted my browser, etc... but when I highlight text in my browser and right click it, no option shows up to "Add to Text Saver" Seems like an amazing concept, as all other kinds of texts savers require you to save as a txt file or into some other account based app. Would instantly be 5 stars for me if this add-on actually worked.

### Version

v1.4.0 I'm assuming. I installed it via the Firefox Addon manager on 9-24-23

**Comment by AndLeaveATrail** [comment]
I also ran a git pull for the latest version (v1.4.0) and this didn't change anything for my right click menu.

**Comment by jiacai2050** [comment]
It looks like this issue

https://discourse.mozilla.org/t/context-menus-not-showing-suddenly-for-my-extension-remindoro/41821/5

Will try submit a patch fix this.

**Comment by AndLeaveATrail** [comment]
Thank you for the response, I happily await to use this extension when it is patched 🙂

**Comment by jiacai2050** [comment]
@AndLeaveATrail Please install v1.4.2 to see if it works for you.
